language: python

python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"

install:
  - pip install nose
  - pip install coveralls
  - pip install .

script:
  - nosetests
  - coverage run --source=fsnav -m nose

after_success:
  - coveralls
